setwd("~/path/to/working/directory")

#install.packages("ggplot2")
#install.packages("ggrepel")
#install.packages("wesanderson")
#install.packages("ghibli")
#install.packages("Redmonder")
#install.packages("rcartocolor")
library(ggplot2)
library(ggrepel)
library(wesanderson)
library(ghibli)
library(Redmonder)
library(rcartocolor)

#create a .csv with Eigen values for "PCo1" and "PCo2" generated by GenAlEx. 
#Add site names as "pop" and add columns for "site" and "depth"
pCoa=read.csv("PCoA.csv")
pCoa

#----------------------------------
##Plotting PCoA
#scale_fill_brewer() uses RColorBrewer palettes. (http://www.sthda.com/english/wiki/colors-in-r)
#scale_fill_manual() allows user defined colors. If not using a pre-defined palette, the number of values must match the number of sites.
#scale_shape_manual() allows user defined shapes. The number of values must match the number of depths.
#scale_size_manual() allows user defined sizes for each shape. The number of values must match the number of depths.
#geom_text_repel() places non-overlaping labels on the plot, specified in ggplot(aes()).

PCoA=ggplot(pCoa,aes(x=PCo1,y=PCo2,label=pop))+
	geom_hline(yintercept=0,color="gray50",size=0.5)+
	geom_vline(xintercept=0,color="gray50",size=0.5)+ 
	geom_point(aes(shape=factor(depth),size=factor(depth),fill=factor(site)),color="black")+	
#	scale_fill_brewer(palette="YlGnBu",name="Reef Site",
#	scale_fill_manual(values=wes_palette(4,name="Zissou",type="continuous"),name="Reef Site",
#	scale_fill_manual(values=ghibli_palette(name="PonyoMedium"),name="Reef Site",
#	scale_fill_manual(values=carto_pal(n=4,name="ag_Sunset"),name="Reef Site",
	scale_fill_manual(values=redmonder.pal(n=4,name="qPBI"),name="Reef Site",
		labels=c("YOUR","SITE","NAMES","HERE"))+  	
	scale_shape_manual(values=c(24,23,22,21),name="Depth",labels=c("YOUR","SAMPLE","DEPTHS","HERE"))+
	scale_size_manual(values=c(5.75,7,7,7))+ 	
	guides(size=F,fill=guide_legend(override.aes=list(size=7,shape=22),order=1),
		shape=guide_legend(override.aes=list(size=c(5.75,7,7,7),fill="white",order=2)),colour=F)+
	xlab("PCo 1 (XX.xx%)")+
	ylab("PCo 2 (XX.xx%)")+
	geom_text_repel(color="black",point.padding=0.3,nudge_x=0.01,segment.color="transparent", size=6)+
	theme_bw()

PCoA+theme(axis.title.x=element_text(color="black",size=24),
		axis.text.x=element_blank(),
		axis.ticks.x=element_blank(),
		axis.line.x=element_blank(),
		axis.title.y=element_text(color="black",size=24),
		axis.text.y=element_blank(),
		axis.ticks.y=element_blank(),
		axis.line.y=element_blank(),
		legend.position="right",
		legend.title=element_text(color="black",size=18),
		legend.text=element_text(color="black",size=16),
		panel.border=element_rect(color="black",size=1.5),
		panel.background=element_blank(),
		plot.background=element_blank(),
		panel.grid.major=element_blank(),
		panel.grid.minor=element_blank())
		
#----------------------------------
##Save plot
#use height=? and width=? to change size of exported image
ggsave("Example_PCoA_plot.tiff", plot=last_plot(),width=12,height=6,dpi=400,device="tiff")
ggsave("Example_PCoA_plot.eps", plot=last_plot(),width=12,height=6,dpi=400,device="eps")